package Kaja.behavior;

/*Generated by MPS */


public class CommentLine_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public CommentLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.CommentLine";
  }
}
