package Kaja.behavior;

/*Generated by MPS */


public class Drop_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public Drop_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.Drop";
  }
}
