package Kaja.behavior;

/*Generated by MPS */


public class East_BehaviorDescriptor extends Direction_BehaviorDescriptor {
  public East_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.East";
  }
}
