package Kaja.behavior;

/*Generated by MPS */


public class EmptyLine_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public EmptyLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.EmptyLine";
  }
}
