package Kaja.behavior;

/*Generated by MPS */


public class Heading_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public Heading_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.Heading";
  }
}
