package Kaja.behavior;

/*Generated by MPS */


public class IsMark_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public IsMark_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.IsMark";
  }
}
