package Kaja.behavior;

/*Generated by MPS */


public class North_BehaviorDescriptor extends Direction_BehaviorDescriptor {
  public North_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.North";
  }
}
