package Kaja.behavior;

/*Generated by MPS */


public class Repeat_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public Repeat_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.Repeat";
  }
}
