package Kaja.behavior;

/*Generated by MPS */


public class Require_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public Require_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.Require";
  }
}
