package Kaja.behavior;

/*Generated by MPS */


public class TraceMessage_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public TraceMessage_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kaja.structure.TraceMessage";
  }
}
