package Kajak.behavior;

/*Generated by MPS */


public class CommandList_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public CommandList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.CommandList";
  }
}
