package Kajak.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Direction_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Direction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.Direction";
  }
}
