package Kajak.behavior;

/*Generated by MPS */


public class IsFull_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public IsFull_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.IsFull";
  }
}
