package Kajak.behavior;

/*Generated by MPS */


public class IsWall_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public IsWall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.IsWall";
  }
}
