package Kajak.behavior;

/*Generated by MPS */


public class LeftTurn_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public LeftTurn_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.LeftTurn";
  }
}
