package Kajak.behavior;

/*Generated by MPS */


public class Not_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public Not_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.Not";
  }
}
