package Kajak.behavior;

/*Generated by MPS */


public class RoutineCall_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public RoutineCall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.RoutineCall";
  }
}
