package Kajak.behavior;

/*Generated by MPS */


public class South_BehaviorDescriptor extends Direction_BehaviorDescriptor {
  public South_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.South";
  }
}
