package Kajak.behavior;

/*Generated by MPS */


public class While_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public While_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Kajak.structure.While";
  }
}
