package JSKajak.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Rect_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("rect(");
    this.append(SPropertyOperations.getString(SLinkOperations.getTarget(node, "x", false), "name"));
    this.append(",");
    this.append(SPropertyOperations.getString(SLinkOperations.getTarget(node, "y", false), "name"));
    this.append(", ");
    this.append("20, 30);");
    this.appendNewLine();
  }
}
