package JSKajak.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class VarDeclaration_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("var ");
    this.append(SPropertyOperations.getString(node, "name"));
    this.append("=");
    this.append("" + SPropertyOperations.getInteger(node, "initialValue"));
    this.append(";");
    this.appendNewLine();
  }
}
