package KajaAndOr.behavior;

/*Generated by MPS */


public class And_BehaviorDescriptor extends LogicalOperator_BehaviorDescriptor {
  public And_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "KajaAndOr.structure.And";
  }
}
