package KajaAndOr.behavior;

/*Generated by MPS */

import Kaja.behavior.LogicalExpression_BehaviorDescriptor;

public abstract class LogicalOperator_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public LogicalOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "KajaAndOr.structure.LogicalOperator";
  }
}
