package KajaAndOr.behavior;

/*Generated by MPS */


public class Or_BehaviorDescriptor extends LogicalOperator_BehaviorDescriptor {
  public Or_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "KajaAndOr.structure.Or";
  }
}
