package JSKajak.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class JSKajak_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("9e572cc0-ff2e-47e1-931a-568ddfca6227(JSKajak)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
