package Kajak.sandbox.sandbox;

/*Generated by MPS */

import JavaKajak.runtime.KajakFrame;

public class Sample extends KajakFrame {
  public Sample() {
  }

  protected void perform() {
    if (canMove()) {
      moveKaja();
      pause();
    } else {
      reportError("Oops, There's a wall in front of me. I can't make a step forward.");
      return;
    }
    for (int indexVariable_kf1bs5_b0 = 0; indexVariable_kf1bs5_b0 < 5; indexVariable_kf1bs5_b0++) {
      if (canMove()) {
        moveKaja();
        pause();
      } else {
        reportError("Oops, There's a wall in front of me. I can't make a step forward.");
        return;
      }
    }
    fill_routine();
    // Imported library routines 
    turnAround_library_routine_from_Common();
    if (canMove()) {
      moveKaja();
      pause();
    } else {
      reportError("Oops, There's a wall in front of me. I can't make a step forward.");
      return;
    }
  }

  public void turnAround_routine() {
    fill_routine();
  }

  public void turnAround2_routine() {
    if (!(isFull())) {
      addMark();
      pause();
    } else {
      reportError("Cannot drop. The cell is already full.");
      return;
    }
    if (!(isFull())) {
      addMark();
      pause();
    } else {
      reportError("Cannot drop. The cell is already full.");
      return;
    }
  }

  public void fill_routine() {
    while (!(isFull())) {
      if (!(isFull())) {
        addMark();
        pause();
      } else {
        reportError("Cannot drop. The cell is already full.");
        return;
      }
    }
  }

  public void turnRight_library_routine_from_Common() {
    for (int indexVariable_gqivph_a0a = 0; indexVariable_gqivph_a0a < 3; indexVariable_gqivph_a0a++) {
      turnLeft();
      pause();
    }
  }

  public void turnAround_library_routine_from_Common() {
    turnLeft();
    pause();
    turnLeft();
    pause();
  }

  public static void main(String[] args) {
    Sample script = new Sample();
    script.initializeComponents();
    script.run();
  }
}
