package KajaSceneConstruction.behavior;

/*Generated by MPS */

import Kaja.behavior.AbstractCommand_BehaviorDescriptor;

public abstract class AbstractBuilderCommand_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public AbstractBuilderCommand_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "KajaSceneConstruction.structure.AbstractBuilderCommand";
  }
}
