package KajaSceneConstruction.behavior;

/*Generated by MPS */


public class DestroyWall_BehaviorDescriptor extends AbstractBuilderCommand_BehaviorDescriptor {
  public DestroyWall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "KajaSceneConstruction.structure.DestroyWall";
  }
}
