package KajaSceneConstruction.behavior;

/*Generated by MPS */


public class DropMark_BehaviorDescriptor extends AbstractBuilderCommand_BehaviorDescriptor {
  public DropMark_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "KajaSceneConstruction.structure.DropMark";
  }
}
