package KajaSceneConstruction.behavior;

/*Generated by MPS */


public class PickMark_BehaviorDescriptor extends AbstractBuilderCommand_BehaviorDescriptor {
  public PickMark_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "KajaSceneConstruction.structure.PickMark";
  }
}
