package Kajak.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"Kajak.structure.AbstractCommand", "Kajak.structure.CommandList", "Kajak.structure.CommentLine", "Kajak.structure.Direction", "Kajak.structure.Drop", "Kajak.structure.East", "Kajak.structure.EmptyLine", "Kajak.structure.Heading", "Kajak.structure.IfStatement", "Kajak.structure.IsMark", "Kajak.structure.IsWall", "Kajak.structure.LeftTurn", "Kajak.structure.LogicalExpression", "Kajak.structure.North", "Kajak.structure.Not", "Kajak.structure.Pick", "Kajak.structure.Repeat", "Kajak.structure.RoutineCall", "Kajak.structure.RoutineDefinition", "Kajak.structure.Script", "Kajak.structure.South", "Kajak.structure.Step", "Kajak.structure.West", "Kajak.structure.While"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("Kajak.structure.AbstractCommand", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("Kajak.structure.CommandList", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      case 2:
        return new CompiledConceptDescriptor("Kajak.structure.CommentLine", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{"text"}, new String[]{});
      case 3:
        return new CompiledConceptDescriptor("Kajak.structure.Direction", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{});
      case 4:
        return new CompiledConceptDescriptor("Kajak.structure.Drop", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      case 5:
        return new CompiledConceptDescriptor("Kajak.structure.East", "Kajak.structure.Direction", false, new String[]{"Kajak.structure.Direction"}, new String[]{}, new String[]{});
      case 6:
        return new CompiledConceptDescriptor("Kajak.structure.EmptyLine", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      case 7:
        return new CompiledConceptDescriptor("Kajak.structure.Heading", "Kajak.structure.LogicalExpression", false, new String[]{"Kajak.structure.LogicalExpression"}, new String[]{}, new String[]{});
      case 8:
        return new CompiledConceptDescriptor("Kajak.structure.IfStatement", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      case 9:
        return new CompiledConceptDescriptor("Kajak.structure.IsMark", "Kajak.structure.LogicalExpression", false, new String[]{"Kajak.structure.LogicalExpression"}, new String[]{}, new String[]{});
      case 10:
        return new CompiledConceptDescriptor("Kajak.structure.IsWall", "Kajak.structure.LogicalExpression", false, new String[]{"Kajak.structure.LogicalExpression"}, new String[]{}, new String[]{});
      case 11:
        return new CompiledConceptDescriptor("Kajak.structure.LeftTurn", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      case 12:
        return new CompiledConceptDescriptor("Kajak.structure.LogicalExpression", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{});
      case 13:
        return new CompiledConceptDescriptor("Kajak.structure.North", "Kajak.structure.Direction", false, new String[]{"Kajak.structure.Direction"}, new String[]{}, new String[]{});
      case 14:
        return new CompiledConceptDescriptor("Kajak.structure.Not", "Kajak.structure.LogicalExpression", false, new String[]{"Kajak.structure.LogicalExpression"}, new String[]{}, new String[]{});
      case 15:
        return new CompiledConceptDescriptor("Kajak.structure.Pick", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      case 16:
        return new CompiledConceptDescriptor("Kajak.structure.Repeat", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{"count"}, new String[]{});
      case 17:
        return new CompiledConceptDescriptor("Kajak.structure.RoutineCall", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{"definition"});
      case 18:
        return new CompiledConceptDescriptor("Kajak.structure.RoutineDefinition", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand", "jetbrains.mps.lang.core.structure.INamedConcept"}, new String[]{}, new String[]{});
      case 19:
        return new CompiledConceptDescriptor("Kajak.structure.Script", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.execution.util.structure.IMainClass"}, new String[]{"startX", "startY"}, new String[]{});
      case 20:
        return new CompiledConceptDescriptor("Kajak.structure.South", "Kajak.structure.Direction", false, new String[]{"Kajak.structure.Direction"}, new String[]{}, new String[]{});
      case 21:
        return new CompiledConceptDescriptor("Kajak.structure.Step", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      case 22:
        return new CompiledConceptDescriptor("Kajak.structure.West", "Kajak.structure.Direction", false, new String[]{"Kajak.structure.Direction"}, new String[]{}, new String[]{});
      case 23:
        return new CompiledConceptDescriptor("Kajak.structure.While", "Kajak.structure.AbstractCommand", false, new String[]{"Kajak.structure.AbstractCommand"}, new String[]{}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
