package JSKajak.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class AbstractStatement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AbstractStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSKajak.structure.AbstractStatement";
  }
}
