package JSKajak.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"JSKajak.structure.DrawFunction", "JSKajak.structure.JSScript", "JSKajak.structure.Rect", "JSKajak.structure.VarDeclaration", "JSKajak.structure.VarReference", "JSKajak.structure.VariableChange"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 1:
        return new JSScript_BehaviorDescriptor();
      case 3:
        return new VarDeclaration_BehaviorDescriptor();
      case 0:
        return new DrawFunction_BehaviorDescriptor();
      case 5:
        return new VariableChange_BehaviorDescriptor();
      case 2:
        return new Rect_BehaviorDescriptor();
      case 4:
        return new VarReference_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
