package JSKajak.behavior;

/*Generated by MPS */


public class DrawFunction_BehaviorDescriptor extends AbstractStatement_BehaviorDescriptor {
  public DrawFunction_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSKajak.structure.DrawFunction";
  }
}
