package JSKajak.behavior;

/*Generated by MPS */


public class Rect_BehaviorDescriptor extends AbstractStatement_BehaviorDescriptor {
  public Rect_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSKajak.structure.Rect";
  }
}
