package JSKajak.behavior;

/*Generated by MPS */


public class VariableChange_BehaviorDescriptor extends AbstractStatement_BehaviorDescriptor {
  public VariableChange_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSKajak.structure.VariableChange";
  }
}
