package JSKajak.behavior;

/*Generated by MPS */


public class VarReference_BehaviorDescriptor extends AbstractStatement_BehaviorDescriptor {
  public VarReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JSKajak.structure.VarReference";
  }
}
